<?php
require 'Personne.php';
require 'Etudiant.php';
require 'Enseignant.php';
require 'AfficheurDePersonne.php';
require 'AfficheurEtudiant.php';
require 'AfficheurEnseignant.php';
$p1 = new Etudiant("Moreliere","26","");
$p2 = new Enseignant("Gauchotte","02","math ");
$p1->prenom="Victor";
$p1->age="19";
$p2->prenom="Remi";
$p2->age="19";
echo("Impression avec echo de p1 : <br>");
echo($p1);
echo("Impression avec print_r de p1 : <br>");
print_r($p2);
echo("<br>");
echo("Impression avec var_dump de p1 : <br>");
var_dump($p2);
echo("<br> On utilise la classe de l'exo 3");
$afficheur1 = new AfficheurEtudiant($p1);
$afficheur2 = new AfficheurEnseignant($p2);
echo("<br> Impression avec 1 en param <br>");
$afficheur1->afficher(1);
echo("<br> Impression avec 2 en param <br>");
$afficheur2->afficher(2);
echo("<br> Impression avec 3 en param <br>");
$afficheur1->afficher(3);
$p1->afficherAge();
$p2->afficherAge();
$p1->punition("Je ne mange pas mon camarade!",10);
$age = $p1->ageAnnee(2054);
echo("Le personnage p1 aura $age ans en 2054");