<?php
require 'src/personne/Personne.php';
require 'src/personne/Etudiant.php';
require 'src/personne/Enseignant.php';
require 'src/afficheur/AfficheurDePersonne.php';
require 'src/afficheur/AfficheurEtudiant.php';
require 'src/afficheur/AfficheurEnseignant.php';
$p1 = new \src\personne\Etudiant("Moreliere","26","");
$p2 = new \src\personne\Enseignant("Gauchotte","02","math ");
$p1->prenom="Victor";
$p1->age="19";
$p2->prenom="Remi";
$p2->age="19";
echo("Impression avec echo de p1 : <br>");
echo($p1);
echo("Impression avec print_r de p1 : <br>");
print_r($p2);
echo("<br>");
echo("Impression avec var_dump de p1 : <br>");
var_dump($p2);
echo("<br> On utilise la classe de l'exo 3");
$afficheur1 = new \src\afficheur\AfficheurEtudiant($p1);
$afficheur2 = new \src\afficheur\AfficheurEnseignant($p2);
echo("<br> Impression avec 1 en param <br>");
$afficheur1->afficher(1);
echo("<br> Impression avec 2 en param <br>");
$afficheur2->afficher(2);
echo("<br> Impression avec 3 en param <br>");
$afficheur1->afficher(3);
$p1->afficherAge();
$p2->afficherAge();
$p1->punition("Je ne mange pas mon camarade!",10);